# Plister OS X preference file
# See https://github.com/benbalter/plister

# System-wide settings stored in /Library/Preferences
system:
  com.apple.commerce:
    AutoUpdate: true
    AutoUpdateRestartRequired: true

  com.apple.SoftwareUpdate:
    AutomaticCheckEnabled: true

# User-specific settings stored in ~/Library/preferences
user:
  com.apple.dock:
    wvous-br-corner: 5 # Bottom right screensaver hot corner
    autohide: true

  com.apple.screensaver:
    askForPassword: 1
    askForPasswordDelay: 0

  com.apple.screencapture:
    location: ~/Desktop
    type: png
    disable-shadow: true

  com.apple.finder:
    DesktopViewSettings:
      IconViewSettings:
        arrangeBy: grid
    FK_StandardViewSettings:
      IconViewSettings:
        arrangeBy: grid
    StandardViewSettings:
      IconViewSettings:
        arrangeBy: grid
    EmptyTrashSecurely: true

  com.google.Chrome:
    AppleEnableSwipeNavigateWithScrolls: false

  com.apple.Safari:
    com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled: false
    com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabledForLocalFiles: false
    com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled: true
    IncludeDevelopMenu: true
    WebKitDeveloperExtrasEnabledPreferenceKey: true

  com.apple.driver.AppleBluetoothMultitouch.mouse:
    MouseButtonMode: TwoButton

  com.apple.print.PrintingPrefs:
    "Quit When Finished": true

  com.apple.SoftwareUpdate:
    ScheduleFrequency: 1

  com.googlecode.iterm2:
    Hotkey: 1
    HotkeyChar: 96
    HotkeyCode: 50
    HotkeyModifiers: 262401
    HotKeyTogglesWindow: 1

  # Global domain-less preferences (NSGlobalDomain)
  .GlobalPreferences:
    NSAutomaticDashSubstitutionEnabled: false
    NSAutomaticQuoteSubstitutionEnabled: false
    WebKitDeveloperExtras: true

# Host specific settings stored in ~/Library/Prefrences/ByHost (currentHost)
host:
  com.apple.screensaver:
    moduleDict:
      moduleName: iLifeSlideshows
      path: "/System/Library/Frameworks/ScreenSaver.framework/Resources/iLifeSlideshows.saver"
      type: 0

  com.apple.ScreenSaver.iLifeSlideShows:
    styleKey: VintagePrints

  com.apple.ScreenSaverPhotoChooser:
    SelectedFolderPath: "/Users/benbalter/github/octodex.github.com/images"
    SelectedSource: 4
    CustomFolderDict:
      identifier: "/Users/benbalter/github/octodex.github.com/images"
      name: octodex
