Layout/LineLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - .pryrc

Lint/UselessAssignment:
  Exclude:
    - .pryrc

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - env/**/*
    - node_modules/**/*
    - Brewfile
