---
configure_dock: true
dockitems_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app/"
    pos: 1
  - name: Spotify
    path: "/Applications/Spotify.app/"
    pos: 5
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app/"
    pos: 6
  - name: Slack
    path: "/Applications/Slack.app/"
    pos: 7
dockitems_remove:
  - Launchpad
  - Mail
  - Contacts
  - Calendar
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - Music
  - Podcasts
  - TV
  - News
  - Books
  - "App Store"
  - "System Settings"

configure_sudoers: false

dotfiles_files:
  - .Brewfile
  - .bundle/config
  - .digrc
  - .gemrc
  - .gitconfig
  - .gitconfig.macos
  - .gitignore
  - .gnupg/gpg-agent.conf
  - .gnupg/gpg.conf
  - .hushlogin
  - .irbrc
  - .mackup.cfg
  - .pryrc
  - .remarkrc
  - .ssh/config
  - .yamllint
  - .zprofile
  - .zshrc
  - .config/mise/config.toml
  - .config/starship.toml
  - Library/Application Support/com.mitchellh.ghostty/config
  - Library/Spelling/LocalDictionary
  - Library/LaunchAgents/com.balter.ben.tmpreaper.plist
  - Library/LaunchAgents/com.balter.ben.update.plist

dotfile_root_dirs:
  - ""
  - "."

homebrew_upgrade_all_packages: false
homebrew_brewfile_dir: "{{ ansible_user_dir }}/.files"
mas_upgrade_all_apps: false
mas_installed_apps: []
mas_signin_dialog: false

directories_to_create:
  - ~/.bundle
  - ~/.config
  - ~/.gnupg
  - ~/.ssh
  - ~/github
  - ~/projects
  - ~/Library/Application Support/com.mitchellh.ghostty
  - ~/Library/LaunchAgents
  - ~/Library/Spelling

macos_defaults:
  system:
    - name: App Store Auto-update
      domain: com.apple.commerce
      key: AutoUpdate
      type: bool
      value: true
    - name: App Store auto restart
      domain: com.apple.commerce
      key: AutoUpdateRestartRequired
      type: bool
      value: true
    - name: App Store Auto check
      domain: com.apple.SoftwareUpdate
      key: AutomaticCheckEnabled
      type: bool
      value: true
    - name: Set lock screen message
      domain: /Library/Preferences/com.apple.loginwindow.plist
      key: LoginwindowText
      value: "Found this computer? Please contact Ben Balter at ben@balter.com."
      type: string
    - name: Enable firewall
      domain: /Library/Preferences/com.apple.alf
      key: globalstate
      value: 1
      type: integer
    - name: Firewall stealth mode
      domain: com.apple.alf
      key: stealthenabled
      type: integer
      value: 1
    - name: Firewall logging
      domain: com.apple.alf
      key: loggingenabled
      type: integer
      value: 1
    - name: Auto-download updates
      domain: com.apple.SoftwareUpdate
      key: AutomaticDownload
      type: integer
      value: 1
    - name: Auto-install macOS updates
      domain: com.apple.SoftwareUpdate
      key: AutomaticallyInstallMacOSUpdates
      type: bool
      value: true
    - name: Install config data updates
      domain: com.apple.SoftwareUpdate
      key: ConfigDataInstall
      type: bool
      value: true
    - name: Install critical security updates
      domain: com.apple.SoftwareUpdate
      key: CriticalUpdateInstall
      type: integer
      value: 1
    - name: Library validation
      domain: com.apple.security.libraryvalidation
      key: DisableLibraryValidation
      type: bool
      value: false
    - name: Disable guest account
      domain: com.apple.MCX
      key: DisableGuestAccount
      type: bool
      value: true
    - name: Disable guest login
      domain: com.apple.loginwindow
      key: GuestEnabled
      type: bool
      value: false
    - name: Login window show name and password
      domain: com.apple.loginwindow
      key: SHOWFULLNAME
      type: bool
      value: true
    - name: Disable password hints
      domain: com.apple.loginwindow
      key: RetriesUntilHint
      type: integer
      value: 0
    - name: Limit ad tracking
      domain: com.apple.AdLib
      key: forceLimitAdTracking
      type: bool
      value: true
  user:
    - name: Hot corner
      domain: com.apple.dock
      key: wvous-br-corner
      type: integer
      value: 5
    - name: Auto hide dock
      domain: com.apple.dock
      key: autohide
      type: bool
      value: true
    - name: Screensaver ask for password
      domain: com.apple.dock
      key: askForPassword
      type: bool
      value: true
    - name: Screensaver delay
      domain: com.apple.dock
      key: askForPasswordDelay
      type: integer
      value: 0
    - name: Screenshot location
      domain: com.apple.screencapture
      key: location
      type: string
      value: ~/Desktop
    - name: Screenshot format
      domain: com.apple.screencapture
      key: type
      type: string
      value: png
    - name: Schedule auto update
      domain: com.apple.SoftwareUpdate
      key: ScheduleFrequency
      type: integer
      value: 1
    - name: Screensaver idle time
      domain: com.apple.screensaver
      key: idleTime
      type: integer
      value: 300
    - name: Secure keyboard entry in Terminal
      domain: com.apple.Terminal
      key: SecureKeyboardEntry
      type: bool
      value: true
