- hosts: localhost
  connection: local

  pre_tasks:
    - name: Include config
      include_vars: "{{ playbook_dir }}/config.yml"
    - name: Include dev config
      include_vars: "{{ playbook_dir }}/config_ci.yml"
      when: lookup('env','CI') == "true"

  tasks:
    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop: "{{ directories_to_create }}"
    - name: Setup Dotfiles
      include_role:
        name: geerlingguy.dotfiles
    - name: Setup Homebrew
      include_role:
        name: geerlingguy.mac.homebrew
    - name: Setup App Store
      include_role:
        name: geerlingguy.mac.mas
      vars:
        mas_installed_apps: []
    - name: Setup Dock
      include_role:
        name: geerlingguy.mac.dock
    - name: Set MacOS system defaults
      community.general.osx_defaults:
        domain: "{{ item.domain }}"
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      become: true
      loop: "{{ macos_defaults.system }}"
    - name: Set MacOS user defaults
      community.general.osx_defaults:
        domain: "{{ item.domain }}"
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      loop: "{{ macos_defaults.user }}"
