- hosts: localhost
  connection: local

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ playbook_dir }}/config.yml"

  tasks:
    - name: Create ssh directory
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: 0755
    - name: Create .bundle directory
      ansible.builtin.file:
        path: ~/.bundle
        state: directory
        mode: 0755
    - name: Setup Dotfiles
      include_role:
        name: geerlingguy.dotfiles
    - name: Setup Homebrew
      include_role:
        name: geerlingguy.mac.homebrew
    - name: Create projects directory
      ansible.builtin.file:
        path: ~/projects
        state: directory
        mode: 0755
    - name: Create github directory
      ansible.builtin.file:
        path: ~/github
        state: directory
        mode: 0755
    - name: Setup App Store
      include_role:
        name: geerlingguy.mac.mas
    - name: Setup Dock
      include_role:
        name: geerlingguy.mac.dock
    - name: App Store Auto-update
      community.general.osx_defaults:
        domain: com.apple.commerce
        key: AutoUpdate
        type: bool
        value: true
      become: true
    - name: App Store auto restart
      community.general.osx_defaults:
        domain: com.apple.commerce
        key: AutoUpdateRestartRequired
        type: bool
        value: true
      become: true
    - name: App Store Auto check
      community.general.osx_defaults:
        domain: com.apple.SoftwareUpdate
        key: AutomaticCheckEnabled
        type: bool
        value: true
      become: true
    - name: Hot corner
      community.general.osx_defaults:
        domain: com.apple.dock
        key: wvous-br-corne
        type: integer
        value: 5
    - name: Auto hide dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true
    - name: Screensaver ask for password
      community.general.osx_defaults:
        domain: com.apple.dock
        key: askForPassword
        type: bool
        value: true
    - name: Screensaver delay
      community.general.osx_defaults:
        domain: com.apple.dock
        key: askForPasswordDelay
        type: integer
        value: 0
    - name: Screenshot locatoin
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: location
        type: string
        value: ~/Desktop
    - name: Screenshot format
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: type
        type: string
        value: png
    - name: Safari disable Java
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled
        type: bool
        value: false
    - name: Safari disable Java for local
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabledForLocalFiles
        type: bool
        value: false
    - name: Safari enable developer tools
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled
        type: bool
        value: true
    - name: Safari enable developer menu
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: IncludeDevelopMenu
        type: bool
        value: true
    - name: Schedule auto update
      community.general.osx_defaults:
        domain: com.apple.SoftwareUpdate
        key: ScheduleFrequency
        type: integer
        value: 1
    - name: Safari Do not track
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: ScheduleFreSendDoNotTrackHTTPHeaderquency
        type: bool
        value: true
    - name: Safari update extensions
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: InstallExtensionUpdatesAutomatically
        type: bool
        value: true
