#!/bin/sh
# Alias all the things!

# Git
alias gs="git status"
alias ga="git add"
alias gad="git add ."
alias gco="git checkout"
alias gc="git commit"
alias gcm="git commit -m"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gp="git push"
alias gd="git diff"
alias gb="gh repo view --web"
alias gr="gh repo view"
alias reset="git reset HEAD --hard; git clean -f -d"
alias clean="git branch --merged | grep -v '\*' | xargs -n 1 git branch -d"
alias ggb="git commit -m ':gem: bump'"
gccd(){ gh repo clone "$1"; cd $(basename "$1") || exit; }
alias branches="git branch -v"

# fasd
alias j='fasd_cd -d'

# Script/*
alias sb="script/bootstrap"
alias sc="script/cibuild"
alias console="script/console"

#simple server
alias server="python -m SimpleHTTPServer"

#ip
alias ip="curl icanhazip.com"
alias flushdns="sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder; echo 'Flushed DNS, btw here is your hosts file just in case:'; cat /etc/hosts"

# .files
alias up="~/.files/script/update"
alias setup="~/.files/script/setup"

# Misc
alias p="cd ~/projects"
alias gg="cd ~/github/github"
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
alias lc='colorls -lA --sd'
