#!/bin/bash
# Init ZSH and the shell environment
# Usage source script/init

# Init some stuff - use (( $+commands[cmd] )) which is faster than `which`
(( $+commands[nodenv] )) && eval "$(nodenv init -)"
(( $+commands[rbenv] )) && eval "$(rbenv init -)"
(( $+commands[fasd] )) && eval "$(fasd --init auto)"
(( $+commands[gh] )) && eval "$(gh completion --shell zsh)"

# Use OSTYPE variable instead of subprocess $(uname)
if [[ "$OSTYPE" == darwin* ]]; then
  (( $+commands[brew] )) && brew command command-not-found-init > /dev/null 2>&1 && eval "$(brew command-not-found-init)"
fi