#!/bin/sh
# Functions shared between script/setup and script/update

link_safe() {
  if [[ ! -f "$HOME_DIR/$1" ]] || [[ $(ls -l "$HOME_DIR/$1" | awk '{print $11}') != "$DOTFILES_ROOT/$1" ]]; then
    echo "Linking $HOME_DIR/$1 to $DOTFILES_ROOT/$1"
    rm -f "$HOME_DIR/$1"
    ln -sf "$DOTFILES_ROOT/$1" "$HOME_DIR/$1"
  fi
}

mkdir_safe() {
  if [[ ! -d "$HOME_DIR/$1" ]]; then
    echo "Creating $1 directory"
    mkdir -p "$HOME_DIR/$1"
  fi
}
