#!/bin/bash
# Set up some common global variables

# Used internally
DOTFILES_ROOT=${DOTFILES_ROOT:-"$HOME/.files"}
export DOTFILES_ROOT

# Setup cli tools
if [ "$(uname)" = "Darwin" ]; then
	HOMEBREW_CASK_OPTS="--appdir=/Applications"
	export HOMEBREW_CASK_OPTS
fi

GOPATH=$HOME/go
export GOPATH

PATH="./bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:$GOPATH/bin:$PATH"
export PATH

# GitHub token with no scope, used to get around API limits
if [ "$(uname)" = "Darwin" ]; then
	HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.token 2>/dev/null)
	export HOMEBREW_GITHUB_API_TOKEN
fi

# ZSH settings and initializations
ZSH=$HOME/.oh-my-zsh
export ZSH

SHELL=$(command -v zsh)
export SHELL

ZSH_THEME=""
export ZSH_THEME

DISABLE_UPDATE_PROMPT=true
export DISABLE_UPDATE_PROMPT

COMPLETION_WAITING_DOTS="true"
export COMPLETION_WAITING_DOTS

# You've got mail
unset MAILCHECK
