#!/bin/bash
# Set up some common global variables

# Used internally
DOTFILES_ROOT=${DOTFILES_ROOT:-"$HOME/.files"}
export DOTFILES_ROOT

# Setup cli tools
HOMEBREW_CASK_OPTS="--appdir=/Applications"
export HOMEBREW_CASK_OPTS

GOPATH=$HOME/go
export GOPATH

PATH="./bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:$GOPATH/bin:/usr/local/opt/gnupg@2.1/bin:$PATH"
export PATH

# GitHub token with no scope, used to get around API limits
# Use OSTYPE variable instead of subprocess $(uname)
if [[ "$OSTYPE" == darwin* ]]; then
  HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.token)
  export HOMEBREW_GITHUB_API_TOKEN
fi

# Fix for global node modules
export NODE_PATH=./node_modules:/usr/local/lib/node_modules

# ZSH settings and initializations
ZSH=$HOME/.oh-my-zsh
export ZSH

# Use existing SHELL or default to zsh path instead of slow $(which zsh)
if [[ -z "$SHELL" ]]; then
  if [[ -x "/opt/homebrew/bin/zsh" ]]; then
    SHELL="/opt/homebrew/bin/zsh"
  elif [[ -x "/usr/local/bin/zsh" ]]; then
    SHELL="/usr/local/bin/zsh"
  else
    SHELL="/bin/zsh"
  fi
fi
export SHELL

ZSH_THEME="robbyrussell"
export ZSH_THEME

DISABLE_UPDATE_PROMPT=true
export DISABLE_UPDATE_PROMPT

COMPLETION_WAITING_DOTS="true"
export COMPLETION_WAITING_DOTS

# You've got mail
unset MAILCHECK
