#!/usr/bin/env ruby

require 'json'
#`apm-beta clean`

plugins = `apm-beta list --installed --bare`
packages = plugins.split("\n").map { |p| p.split('@').first }.sort_by(&:downcase)
path = File.expand_path "../.atom/packages.cson", __dir__
File.write path, "packages: #{JSON.pretty_generate(packages).gsub(",", "")}"
