#!/bin/bash

# Load libs
export DOTFILES_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DOTFILES_ROOT/lib/zsh.zsh"
source "$DOTFILES_ROOT/lib/aliases.zsh"
source ~/.iterm2_shell_integration.zsh

# Set Atom as the default editor
export EDITOR='atom -w'

# You've got mail
unset MAILCHECK

# Setup cli tools
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export PATH="./bin:/usr/local/sbin:$PATH"

# GitHub token with no scope, used to get around API limits
export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.token)

# Init some stuff
if brew command command-not-found-init > /dev/null; then eval "$(brew command-not-found-init)"; fi
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi
if which rbenv > /dev/null;  then eval "$(rbenv init -)"; fi
if which fasd > /dev/null; then eval "$(fasd --init auto)"; fi
