#!/bin/bash
# Set up a symlink to the dotfiles repo
# Usage: script/link-safe <PATH>

set -e

# shellcheck source=lib/globals
source "/$HOME/.files/lib/globals"

# shellcheck source=lib/functions
source "/$DOTFILES_ROOT/lib/functions"

link_safe "$@"
