#!/bin/sh


title () {
  echo "\n"
  echo "-------------------------------"
  echo $1
  echo "-------------------------------"
  echo "\n"
}

title "Updating Homebrew..."
brew update
brew upgrade

title "Updating App Store apps"
softwareupdate --install --all

title "Updating Atom..."
apm update
apm upgrade

title "Updating system Ruby gems..."
gem update

title "Updating global Node packages..."
npm update --global
npm upgrade --global
