#!/bin/sh


title () {
  echo "\n"
  echo "-------------------------------"
  echo $1
  echo "-------------------------------"
  echo "\n"
}

title "Updating Homebrew..."
brew update
brew upgrade

title "Updating App Store apps"
softwareupdate --install --all

title "Updating Atom..."
apm update
apm upgrade

title "Updating global Node packages..."
npm update --global
npm upgrade --global

latest_ruby=$(rbenv install -l | grep -v - | tail -1 )
latest_ruby="$(echo "${latest_ruby}" | tr -d '[[:space:]]')"
if [ $(rbenv global) != $latest_ruby ]; then
  title "Updating Ruby..."
  rbenv install $latest
  rbenv global $latest
  rbenv rehash
  gem install bundler
fi

title "Updating system Ruby gems..."
gem update --system
gem update
