#!/bin/bash
# Sets up atom config and plugins

# shellcheck source=lib/globals
source "/$HOME/.files/lib/globals"

# shellcheck source=lib/functions
source "/$DOTFILES_ROOT/lib/functions"

mkdir_safe .atom
link_safe .atom/config.cson
link_safe .atom/keymap.cson
link_safe .atom/packages.cson

brew cask install atom-beta
apm-beta install $(sed '$d' < .atom/packages.cson | sed "1d" | tr -d '\n' | tr -d '"')
