#!/bin/bash
# Sets up atom config and plugins

exit 0

# shellcheck source=lib/globals
source "/$HOME/.files/lib/globals"

# shellcheck source=lib/functions
source "/$DOTFILES_ROOT/lib/functions"

mkdir_safe .atom
link_safe .atom/config.cson
link_safe .atom/keymap.cson

brew cask install atom-beta
apm install --packages-file "$DOTFILES_ROOT/.atom/packages.txt"
