#!/bin/sh
# Setup up Bundler

if [[ -d "/workspaces/.codespaces/.persistedshare/dotfiles/" ]]; then
  export DOTFILES_ROOT="/workspaces/.codespaces/.persistedshare/dotfiles/"
else 
  export DOTFILES_ROOT="$HOME/.files"
fi 

# shellcheck source=lib/globals
source "$DOTFILES_ROOT/lib/globals"

# shellcheck source=lib/functions
source "$DOTFILES_ROOT/lib/functions"

mkdir_safe .bundle
link_safe .bundle/config
