#!/bin/sh
# Setup up Bundler

# shellcheck source=lib/globals
source "/$HOME/.files/lib/globals"

# shellcheck source=lib/functions
source "/$DOTFILES_ROOT/lib/functions"

mkdir_safe .bundle
link_safe .bundle/config
