#!/usr/bin/env ruby

exit 0

require 'json'

exit 0

path = File.expand_path '../../package.json', File.dirname(__FILE__)
packages = JSON.parse File.read(path)
packages = packages['dependencies'].map { |package, _version| package }.join(' ')
system "npm install -g #{packages}"
