#!/bin/sh

exit 0

npm install prey -g

if sudo prey config check; then
  true
else
  sudo prey config account setup
  sudo prey config hooks post_install
  sudo prey config plugins enable control-panel
  sudo prey config gui
fi
