#!/bin/bash
# Setup up rbenv

if [[ -d "/workspaces/.codespaces/.persistedshare/dotfiles/" ]]; then
  export DOTFILES_ROOT="/workspaces/.codespaces/.persistedshare/dotfiles/"
else 
  export DOTFILES_ROOT="$HOME/.files"
fi 

# shellcheck source=lib/globals
source "$DOTFILES_ROOT/lib/globals"
source "$DOTFILES_ROOT/lib/functions"

command -v rbenv >/dev/null 2>&1 || { echo >&2 brew install rbenv; }

if [ $(rbenv which ruby) == "/usr/bin/ruby" ]; then
  eval "$(rbenv init -)"
fi

link_safe default_gems $(rbenv root)

echo "Latest Ruby version is $(latest_ruby)"
echo "Global ruby version is $(rbenv global)"

if [ "$(rbenv global)" = "system" ]; then
  brew install ruby-build
  rbenv install "$(latest_ruby)"
  rbenv global "$(latest_ruby)"
  rbenv rehash
fi

curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
 