#!/bin/sh
# Set up Rbenv, bundler, and system gems

script/setup/rbenv
script/setup/bundler

if [ $(rbenv which ruby) == "/usr/bin/ruby" ]; then
  eval "$(rbenv init -)"
fi

echo "Using Ruby $(rbenv which ruby)"
$(rbenv which gem) update --system --no-document
