#!/bin/sh
# Setups up symlinks from .files to home directory

# shellcheck source=lib/globals
source "$DOTFILES_ROOT/lib/globals"

# shellcheck source=lib/functions
source "$DOTFILES_ROOT/lib/functions"

link_safe .gitconfig
link_safe .gitignore
link_safe .irbrc
link_safe .pryrc
link_safe .Brewfile
link_safe .gemrc
link_safe .mackup.cfg
link_safe .digrc
link_safe .osx.yml
link_safe .remarkrc
link_safe .hushlogin

mkdir_safe "Library/LaunchAgents/"
link_safe Library/LaunchAgents/com.balter.ben.tmpreaper.plist
link_safe Library/LaunchAgents/com.balter.ben.update.plist

mkdir_safe "Library/Spelling/"
link_safe Library/Spelling/LocalDictionary

mkdir_safe projects
mkdir_safe github

mkdir_safe .ssh
link_safe .ssh/config

mkdir_safe heroku
link_safe heroku/config.json

echo "Symlinks set."
