#!/bin/bash
# Prompts to create a `~/.token` file with a GitHub public token

if [ ! -f "$HOME/.token" ]; then
  echo "Create a GitHub Personal Access Token with *public* scope"
  echo "by going to https://github.com/settings/tokens"
  echo "and enter it below:"

  if [ "$TRAVIS" != "true" ] && [ "$CODESPACES" != "true" ]; then
    read -r token
  else
    token=""
  fi

  echo "$token" > "$HOME/.token"
  echo "Token saved as ~/.token."
else
  echo "Token already set as ~/.token."
fi
