name: CI
on: [push]
jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pip Cache
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Venv cache
        uses: actions/cache@v3
        with:
          path: ./env
          key: ${{ runner.os }}-env-${{ hashFiles('requirements.txt') }}

      - name: Ansible cache
        uses: actions/cache@v3
        with:
          path: ~/.ansible
          key: ${{ runner.os }}-ansible-${{ hashFiles('requirements.yml') }}

      - name: Bootstrap
        run: script/bootstrap

      - name: Run playbook
        run: script/ansible

  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pip Cache
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Venv cache
        uses: actions/cache@v3
        with:
          path: ./env
          key: ${{ runner.os }}-env-${{ hashFiles('requirements.txt') }}

      - name: Ansible cache
        uses: actions/cache@v3
        with:
          path: ~/.ansible
          key: ${{ runner.os }}-ansible-${{ hashFiles('requirements.yml') }}

      - name: Bootstrap
        run: script/bootstrap

      - name: lint
        run: script/lint
