name: CI
on: [push]
permissions:
  contents: read

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  bootstrap:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pip Cache
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Venv cache
        uses: actions/cache@v4
        with:
          path: ./env
          key: ${{ runner.os }}-env-${{ hashFiles('requirements.txt') }}

      - name: Ansible cache
        uses: actions/cache@v4
        with:
          path: ~/.ansible
          key: ${{ runner.os }}-ansible-${{ hashFiles('requirements.yml') }}

      - name: Bootstrap
        run: script/bootstrap

      - name: Upload venv
        uses: actions/upload-artifact@v4
        with:
          name: venv
          path: env/

  test:
    needs: bootstrap
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ansible cache
        uses: actions/cache@v4
        with:
          path: ~/.ansible
          key: ${{ runner.os }}-ansible-${{ hashFiles('requirements.yml') }}

      - name: Download venv
        uses: actions/download-artifact@v8
        with:
          name: venv
          path: env/

      - name: Run playbook
        run: script/ansible

  lint:
    needs: bootstrap
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ansible cache
        uses: actions/cache@v4
        with:
          path: ~/.ansible
          key: ${{ runner.os }}-ansible-${{ hashFiles('requirements.yml') }}

      - name: Download venv
        uses: actions/download-artifact@v8
        with:
          name: venv
          path: env/

      - name: Lint
        run: script/lint

  unit-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install bats-core yq

      - name: Run tests
        run: script/test
