name: CI
on: [push]
jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: ./venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - uses: actions/setup-python@v2
      - run: script/bootstrap
      - run: script/cibuild
      - run: script/ansible
