name: CI
on: [push]
jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: script/bootstrap
      - run: script/cibuild
