name: CI
on: [push]
jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      #  - name: Set up Homebrew
      #   uses: Homebrew/actions/setup-homebrew@master
      #      - uses: actions/cache@v2
      #       with:
      #        path: ~/.cache/pip
      #       key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #      restore-keys: |
      #       ${{ runner.os }}-pip-
      - run: script/bootstrap
      - run: script/cibuild
      - run: script/ansible
