name: CI
on: [push]
jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pip Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Python cache
        uses: actions/cache@v2
        with:
          path: ./env
          key: ${{ runner.os }}-env-${{ hashFiles('requirements.txt') }}

      - name: Ansible cache
        uses: actions/cache@v2
        with:
          path: ~/.ansible
          key: ${{ runner.os }}-ansible-${{ hashFiles('requirements.yml') }}

      - name: Bootstrap
        run: script/bootstrap

      - name: Lint
        run: script/cibuild

      - name: Run playbook
        run: script/ansible
